### ISSUE TITLE
Survey slides should extend to the height of the screen

### ISSUE THREAD

**Issue by olivierobert** [HelloCore/NimbleSurvey#2]
Only one slide should be displayed with the floating button "Take Survey" set to be at the bottom of the screen.

The current implementation shows the top of the next slide:

![glass](https://cloud.githubusercontent.com/assets/696529/23353253/1a4644d6-fcfe-11e6-9d5a-0a4b13cc7ef0.png)

**Comment by HelloCore** [comment]
I really apologized for this issue.
To be honest, I completely forgot to test layout on other devices.
However, I'm going to test on all screen size after I fix it.
